
export const PlanetData = [
    {
        title: "Earth",
        link: "EarthClouds_1_12756.glb",
        Description: "Earth is the third planet from the sun and the fifth largest in the solar system. Just slightly larger than nearby Venus, Earth is the biggest of the terrestrial planets. ",
        small_desc: "Earth—our home planet—is the only place we know of so far that’s inhabited by living things. It's also the only planet in our solar system with liquid water on the surface.",
        slogan: "Our Home Planet",
        orbit_dist: "149,598,262",
        orbit_dist_au: "1.000",
        radius: "6,371.00",
        mass: "5,972,190,000,000,000,000,000,000",
        density: "5.513",
        volume: "1,083,206,916,846",
        surface_g: "9.80665",
        surface_g_comp: "Earth Gravity is 9.80665 G",
        image: "Earth.jpg"

    },
    {
        title: "Mars",
        link: "/Mars_1_6792.glb",
        Description: "Mars may have once been a wet world like Earth. Where did the water go?",
        small_desc: "Mars is a dusty, cold, desert world with a very thin atmosphere. There is strong evidence Mars was – billions of years ago – wetter and warmer, with a thicker atmosphere.",
        slogan: "The Red Planet",
        orbit_dist: "227,943,824",
        orbit_dist_au: "1.523662",
        radius: "3,389.5",
        mass: "641,693,000,000,000,000,000,000",
        density: "3.934",
        volume: "163,115,609,799",
        surface_g: "3.71",
        surface_g_comp: "If you weigh 100 pounds on Earth, you would weigh 38 pounds on Mars.",
        image: "Mars.png"
    },
    {
        title: "Jupiter",
        link: "/Jupiter_1_142984.glb",
        Description: "Jupiter is the fifth planet from our sun and the largest planet in the solar system. Jupiter's stripes and swirls are cold, windy clouds of ammonia and water. The atmosphere is mostly hydrogen and helium, and its iconic Great Red Spot is a giant storm.",
        small_desc: "Jupiter is more than twice as massive than the other planets of our solar system combined. The giant planet's Great Red spot is a centuries-old storm bigger than Earth.",
        slogan: "King of the Planets",
        orbit_dist: "778,340,821",
        orbit_dist_au: "5.2028870",
        radius: "69,911",
        mass: "1,898,130,000,000,000,000,000,000,000",
        density: "1.326",
        volume: "1,431,281,810,739,360",
        surface_g: "24.79",
        surface_g_comp: "If you weigh 100 pounds on Earth, you would weigh 253 pounds on Jupiter.",
        image: "Jupiter.jpg"
    },
    {
        title: "Mercury",
        link: "/Mercury_1_4878.glb",
        Description: "Mercury's eccentric orbit takes the small planet as close as 47 million km (29 million miles) and as far as 70 million km (43 million miles) from the sun. If one could stand on the scorching surface of Mercury when it is at its closest point  to the sun,",
        small_desc: "Mercury—the smallest planet in our solar system and closest to the Sun—is only slightly larger than Earth's Moon. Mercury is the fastest planet, zipping around the Sun every 88 Earth days.",
        slogan: "The Swiftest Planet",
        orbit_dist: "57,909,227",
        orbit_dist_au: "0.38709927",
        radius: "2,439.7",
        mass: "330,104,000,000,000,000,000,000",
        density: "5.427",
        volume: "60,827,208,742",
        surface_g: "3.7",
        surface_g_comp: "If you weigh 100 pounds on Earth, you would weigh 38 pounds on Mercury.",
        image: "Mercury.jpg"
    },
    {
        title: "Neptune",
        link: "/Neptune_1_49528.glb",
        Description: "Dark, cold and whipped by supersonic winds, Neptune is the last of the hydrogen and helium gas giants in our solar system. More than 30 times as far from the sun as Earth, the planet takes almost 165 Earth years to orbit our sun.",
        small_desc: "Neptune—the eighth and most distant major planet orbiting our Sun—is dark, cold and whipped by supersonic winds. It was the first planet located through mathematical calculations. ",
        slogan: "The Windiest Planet",
        orbit_dist: "4,498,396,441",
        orbit_dist_au: "3.0069923 x 10<SUP>1</SUP>",
        radius: "24,622",
        mass: "102,410,000,000,000,000,000,000,000",
        density: "1.638",
        volume: "62,525,703,987,421",
        surface_g: "11.15",
        surface_g_comp: "If you weigh 100 pounds on Earth, you would weigh 114 pounds on Neptune.",
        image: "Neptune.jpg"
    },
    {
        title: "Saturn",
        link: "/Saturn_1_120536.glb",
        Description: "The second largest planet in our solar system, adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings  -- made of chunks of ice and rock -- but none are as spectacular as Saturn's.",
        small_desc: "Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system. The other giant planets have rings, but none are as spectacular as Saturn's. ",
        slogan: "Jewel of Our Solar System",
        orbit_dist: "1,426,666,422",
        orbit_dist_au: "9.53667594",
        radius: "58,232",
        mass: "568,319,000,000,000,000,000,000,000",
        density: "0.687",
        volume: "827,129,915,150,897",
        surface_g: "10.4*",
        surface_g_comp: "If you weigh 100 pounds on Earth, you would weigh about 107 pounds on Saturn (at the equator). *Derived from a 1 bar radius of 60,268 km.",
        image: "Saturn.jpg"
    },
    {
        title: "Sun",
        link: "/Sun_1_1391000.glb",
        Description:"The Sun holds the solar system together, keeping everything – from the biggest planets to the smallest debris – in its orbit.",
        small_desc: "",
        slogan: "",
        orbit_dist: "",
        orbit_dist_au: "9.53667594",
        radius: "",
        mass: "",
        density: "",
        volume: "",
        surface_g: "",
        surface_g_comp: "",
        image: "Sun.jpg"
        
    },
    {
        title: "Uranus",
        link: "/Uranus_1_51118.glb",
        Description: "The seventh planet from the sun with the third largest diameter in our solar system, Uranus is very cold and windy. The ice giant is surrounded by 13 faint rings and 27 small moons as it rotates at a nearly 90-degree angle from the plane of its orbit.",
        small_desc: "Uranus—seventh planet from the Sun—rotates at a nearly 90-degree angle from the plane of its orbit. This unique tilt makes Uranus appear to spin on its side.",
        slogan: "The Sideways Planet",
        orbit_dist: "2,870,658,186",
        orbit_dist_au: "1.9189165 x 10<SUP>1</SUP>",
        radius: "25,362",
        mass: "86,810,300,000,000,000,000,000,000",
        density: "1.270",
        volume: "68,334,355,695,584",
        surface_g: "8.87",
        surface_g_comp: "If you weigh 100 pounds on Earth, you would weigh 91 pounds on Uranus.",
        image: "Uranus.jpg"
    },
    {
        title: "Venus",
        link: "/Venus_1_12103.glb",
        Description: "Venus is the second planet from the sun and our closest planetary neighbor. Similar in structure and size to Earth, Venus spins slowly in the opposite direction most planets do.",
        small_desc: "Venus spins slowly in the opposite direction from most planets. A thick atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system.",
        slogan: "Planetary Hot Spot",
        orbit_dist: "108,209,475",
        orbit_dist_au: "7.2333566 x 10<SUP>-1</SUP>",
        radius: "6,051.8",
        mass: "4,867,320,000,000,000,000,000,000",
        density: "5.243",
        volume: "928,415,345,893",
        surface_g: "8.87",
        surface_g_comp: "If you weigh 100 pounds on Earth, you would weigh 91 pounds on Venus.",
        image: "Venus.jpg"
    },
    {
        title: "Michael",
        link: "/",
        Description: "Michael is an exceptional leader who consistently demonstrates his ability to lead by example. His leadership style is inclusive, collaborative, and focused on achieving results while ensuring the well-being of his team members. Michael's strategic vision and ability to communicate it effectively have been instrumental in the success of our organization. He is a skilled problem solver who is always willing to lend his expertise to help others overcome challenges. Michael's dedication to his team's professional development and growth is inspiring and has resulted in high levels of engagement and retention among team members.",
        small_desc: "Michael is an exceptional leader who consistently demonstrates his ability to lead by example. His leadership style is inclusive, collaborative, and focused on achieving results while ensuring the well-being of his team members. Michael's strategic vision and ability to communicate it effectively have been instrumental in the success of our organization. He is a skilled problem solver who is always willing to lend his expertise to help others overcome challenges. Michael's dedication to his team's professional development and growth is inspiring and has resulted in high levels of engagement and retention among team members.",
        slogan: "The Legendary Scrum Master",
        orbit_dist: "108,209,475",
        orbit_dist_au: "7.2333566 x 10<SUP>-1</SUP>",
        radius: "6,051.8",
        mass: "4,867,320,000,000,000,000,000,000",
        density: "5.243",
        volume: "928,415,345,893",
        surface_g: "8.87",
        surface_g_comp: "You will be missed...",
        image: ""
    }
];